// <auto-generated />
using CSG.Test.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSG.Test.WebApi.Migrations
{
    [DbContext(typeof(CsgDbContext))]
    partial class CsgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSG.Test.WebApi.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Location = "Sydney",
                            Name = "Executive"
                        },
                        new
                        {
                            Id = 2L,
                            Location = "Sydney",
                            Name = "Production"
                        },
                        new
                        {
                            Id = 3L,
                            Location = "Cape Town",
                            Name = "Resources"
                        },
                        new
                        {
                            Id = 4L,
                            Location = "Texas",
                            Name = "Technical"
                        },
                        new
                        {
                            Id = 5L,
                            Location = "Paris",
                            Name = "Management"
                        });
                });

            modelBuilder.Entity("CSG.Test.WebApi.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Salary")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DepartmentId = 1L,
                            Name = "Candice",
                            Salary = 4685L
                        },
                        new
                        {
                            Id = 2L,
                            DepartmentId = 2L,
                            Name = "Julia",
                            Salary = 2559L
                        },
                        new
                        {
                            Id = 3L,
                            DepartmentId = 4L,
                            Name = "Bob",
                            Salary = 4405L
                        },
                        new
                        {
                            Id = 4L,
                            DepartmentId = 1L,
                            Name = "Scarlet",
                            Salary = 2350L
                        },
                        new
                        {
                            Id = 5L,
                            DepartmentId = 4L,
                            Name = "Ilena",
                            Salary = 1151L
                        });
                });

            modelBuilder.Entity("CSG.Test.WebApi.Models.Employee", b =>
                {
                    b.HasOne("CSG.Test.WebApi.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
